version: "3.8"
services:
  website:
    image: python_index_website:latest
    container_name: python_index_website
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_PASSWORD: 123abc
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_DATABASE: postgres
    ports:
      - "6969:6969"
    restart: always