name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
        - uses: actions/checkout@v2

        - name: Build and Publish latest Docker image
          uses: VaultVulp/gp-docker-action@1.1.12
          with:
              github-token: ${{ secrets.GITHUB_TOKEN }}
              image-name: python-import-index
              dockerfile: Dockerfile